name: Docker & EC2 CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: devraul/iplease-eureka-server
  DOCKER_IMAGE_TAG: ${{ env.GITHUB_RUN_ID }}
  DOCKER_CONTAINER_NAME: eureka-server
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # setup java
    - name: setup JDK 17
      uses: actions/setup-java@v2
      with: 
        java-version: '17'
        distribution: 'adopt'
    # prepare execute  
    - name: grant execute permission to gradlew
      run: chmod +x gradlew
    # test
    - name: test with gradle
      run: ./gradlew test
    # build
    - name: build with gradle
      run: ./gradlew build -x test
    - name: login to docker
      run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: build docker image
      run: sudo docker build --tag ${DOCKER_IMAGE_NAME}:${github .
    - name: push docker image
      run: sudo docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
  cd:
    runs-on: [ self-hosted, iplease-eureka ]
    needs: ci
    steps: 
      - uses: actions/checkout@v3
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      # setup java
      - name: setup JDK 17
        uses: actions/setup-java@v2
        with: 
          java-version: '17'
          distribution: 'adopt'
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: pull image from docker
        run: sudo docker pull ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
      - name: run docker container from image
        run: |
          docker stop ${DOCKER_CONTAINER_NAME} && docker rm ${DOCKER_CONTAINER_NAME}
          docker run -d -p 10010:10010 \
          --env-file=${{ secrets.DOCKER_ENV_FILE_PATH }} \
          --network ${{ secrets.DOCKER_NETWORK }} \
          --ip ${{ secrets.DOCKER_IP }} \
          --name ${DOCKER_CONTAINER_NAME} \
          --restart always \
          ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
