name: Docker Image CI with gradle task

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: devraul/iplease-eureka-server:$(date +%s)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # setup java
    - name: setup JDK 17
      uses: actions/setup-java@v2
      with: 
        java-version: '17'
        distribution: 'adopt'
    # prepare execute  
    - name: grant execute permission to gradlew
      run: chmod +x gradlew
    # test
    - name: test with gradle
      run: ./gradlew test
    # build
    - name: build with gradle
      run: ./gradlew build -x test
    - name: login to docker
      run: sudo docker login -u ${{ secret.DOCKER_USERNAME }} -p ${{ secret.DOCKER_PASSWORD }}
    - name: build docker image
      run: sudo docker build --tag ${DOCKER_IMAGE_NAME} .
    - name: push docker image
      run: sudo docker push ${DOCKER_IMAGE_NAME}
      
      
